services:
  mysql:
    image: mysql:8
    container_name: mysql_dev
    environment:
      TZ: America/Sao_Paulo  
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: catalogoDB
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: